"""Add is_uploaded column to files

Revision ID: 37d385ef75a8
Revises: a7d4f58d76c0
Create Date: 2023-05-21 15:15:49.144519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37d385ef75a8"
down_revision = "a7d4f58d76c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("is_uploaded", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "is_uploaded")
    # ### end Alembic commands ###
