"""Add sessions

Revision ID: a05b3b4fb57a
Revises: 56ea7a9ed930
Create Date: 2023-05-19 18:44:39.814743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a05b3b4fb57a"
down_revision = "56ea7a9ed930"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
