"""Add stuff

Revision ID: a8d1f42eda11
Revises: efb94196c784
Create Date: 2023-05-21 17:00:26.698839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8d1f42eda11"
down_revision = "efb94196c784"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_storage_base_dirs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_storage_base_dirs_path"),
        "user_storage_base_dirs",
        ["path"],
        unique=False,
    )
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_index(
        op.f("ix_user_storage_base_dirs_path"),
        table_name="user_storage_base_dirs",
    )
    op.drop_table("user_storage_base_dirs")
    # ### end Alembic commands ###
